#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TheBucketList8.Resource", IsApplication=true)]

namespace TheBucketList8
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int kategorija_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int civ_border_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int civ_border_overlay = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int civ_border_width = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int civ_fill_color = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_bucketlist = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_bucketlist = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_bucketlist = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_bucketlist = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_bucketlist = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_bucketlist = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int add = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_bucketlist = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_default_bucketlist = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_focused_bucketlist = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_cab_done_pressed_bucketlist = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_bottom_bucketlist = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cab_background_top_bucketlist = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int @checked = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int dodaj = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int list_focused_bucketlist = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int list_pressed_bucketlist = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int menu_dropdown_panel_bucketlist = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ostvarenoFALSE = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ostvarenoTRUE = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int plus = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int profile = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int progress_bg_bucketlist = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int progress_horizontal_bucketlist = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int progress_primary_bucketlist = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int progress_secondary_bucketlist = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int refresh = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int selectable_background_bucketlist = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int spinner_ab_default_bucketlist = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int spinner_ab_disabled_bucketlist = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int spinner_ab_focused_bucketlist = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int spinner_ab_pressed_bucketlist = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int spinner_background_ab_bucketlist = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_indicator_ab_bucketlist = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_selected_bucketlist = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_selected_focused_bucketlist = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_selected_pressed_bucketlist = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tab_unselected_bucketlist = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tab_unselected_focused_bucketlist = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int tab_unselected_pressed_bucketlist = 2130837544;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070017
			public const int btnReg = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int btnSlika = 2131165205;
			
			// aapt resource value: 0x7f07000a
			public const int button1 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int button2 = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int editText1 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int editText2 = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int imageView1 = 2131165191;
			
			// aapt resource value: 0x7f070016
			public const int imgReg = 2131165206;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout1 = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int naslovText = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int odaberiButton = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int odustaniButton = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int opisText = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int scrollView1 = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int slikaView = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int spinner1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int spremiButton = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int txtImeReg = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int txtMotoReg = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int txtOMeniReg = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int txtPonoviReg = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int txtPrezimeReg = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int txtUsernameReg = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int txtZaporkaReg = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int create = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int register = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int Add = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int All = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Profile = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int kategorija_prompt = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBar_Solid_Bucketlist = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int ActionBar_Transparent_Bucketlist = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int ActionBarTabStyle_Bucketlist = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int ActionButton_CloseMode_Bucketlist = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int DropDownListView_Bucketlist = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int DropDownNav_Bucketlist = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int PopupMenu_Bucketlist = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int ProgressBar_Bucketlist = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Bucketlist = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int Theme_Bucketlist_Widget = 2131099657;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
